stages:
  - build
  - test
  - deploy

variables:
  # Define environment variables here if needed
  NODE_ENV: 'production'

before_script:
  - echo "Setting up the environment..."

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - npm test
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - npm run deploy
  only:
    - main
